name: Run Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: server  # Set the working directory to 'server'

      - name: Run tests
        run: npm test
        working-directory: server  # Set the working directory to 'server'
